export const SET_PROJECTS_INFO = 'SET_PROJECTS_INFO'
export const IS_PROJECTS_LOADING = 'IS_PROJECTS_LOADING'
export const IS_PROJECTS_REFRESHING = 'IS_PROJECTS_REFRESHING'
export const IS_PROJECTS_ERROR = 'IS_PROJECTS_ERROR'

export const IS_RESERVES_LOADING = 'IS_RESERVES_LOADING'
export const IS_RESERVES_REFRESHING = 'IS_RESERVES_REFRESHING'
export const IS_RESERVES_ERROR = 'IS_RESERVES_ERROR'
export const SET_RESERVES = 'SET_RESERVES'
export const SET_FILTERED_RESERVES = 'SET_FILTERED_RESERVES'

export const ON_CHANGE_MONTH_FILTER = 'ON_CHANGE_MONTH_FILTER'
export const SET_MONTH_FILTER_INITIAL = 'SET_MONTH_FILTER_INITIAL'
export const SET_FILTER = 'SET_FILTER'
export const IS_FILTER_LOADING = 'IS_FILTER_LOADING'
export const IS_FILTER_REFRESHING = 'IS_FILTER_REFRESHING'
export const IS_FILTER_ERROR = 'IS_FILTER_ERROR'

export const SET_USERS_DICT = 'SET_USERS_DICT'
export const SET_STATES_DICT = 'SET_STATES_DICT'



